version: '3.1'

services:
  postgres:
    image: postgres
    build: postgres/
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/dumps:/dumps
    restart: on-failure
    networks:
      - backend
  app:
    image: whiskey_app
    build: ./
    tty: true
    volumes:
      - "./:/whiskey_app"
    env_file: .env
    links:
      - postgres
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "3000:3000"
    networks: 
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres_data: {}
